### ISSUE TITLE
Black Box

### ISSUE THREAD

**Issue by SushmaDG** [manikantapujar/ROS-Survo#2]
![black box](https://cloud.githubusercontent.com/assets/22175791/19837283/ced01d12-9edc-11e6-85d5-d54a2b10986f.PNG)

**Comment by SushmaDG** [comment]
![white box](https://cloud.githubusercontent.com/assets/22175791/19837294/1ab4289a-9edd-11e6-96e7-0a729f26e99f.png)

**Comment by manikantapujar** [comment]
In black box  environmental  feature out come will be the same environment
The input is material and output must be material itself so the material is "ground or (environment)"

**Comment by manikantapujar** [comment]
so can we add that in both Black Box and White Box

**Comment by SushmaDG** [comment]
the output will be in form of display on operators screen so it is written like that. How will the material output be environment!!!!

**Comment by manikantapujar** [comment]
The bot will move or slide on environment so 
material for our bot is environment so i  have asked
